//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqTutorials
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentsID { get; set; }
        public string Comments { get; set; }
    }
}
