//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqTutorials
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFilter
    {
        public string FilterDesc { get; set; }
        public Nullable<System.DateTime> FilterFrom { get; set; }
        public Nullable<System.DateTime> FilterTo { get; set; }
        public int orderno { get; set; }
    }
}
