//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqTutorials
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public Nullable<System.DateTime> due_datetime { get; set; }
        public Nullable<int> total_count { get; set; }
        public int ID { get; set; }
    }
}
